language: php

php:
  - 5.3

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - wget https://github.com/cakephp/cakephp/tarball/2.1.3 -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - echo "<?php
    App::build(array(
    'Plugin' => array(dirname(__FILE__) . DS . '../../../'),
    ));
    CakePlugin::loadAll();
    " > cakephp/app/Config/bootstrap.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > cakephp/app/Config/database.php
  - cat cakephp/app/Config/bootstrap.php
  - cd ./cakephp

script:
  - ./lib/Cake/Console/cake test Yacsv home/vagrant/builds/k1LoW/Yacsv/Test/Case/Model/Behavior/ImporterBehavior --stderr